/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreakRouteImport } from './routes/streak'
import { Route as StakesRouteImport } from './routes/stakes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifyStakeIdRouteImport } from './routes/verify.$stakeId'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'

const StreakRoute = StreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const StakesRoute = StakesRouteImport.update({
  id: '/stakes',
  path: '/stakes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyStakeIdRoute = VerifyStakeIdRouteImport.update({
  id: '/verify/$stakeId',
  path: '/verify/$stakeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/stakes': typeof StakesRoute
  '/streak': typeof StreakRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/verify/$stakeId': typeof VerifyStakeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/stakes': typeof StakesRoute
  '/streak': typeof StreakRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/verify/$stakeId': typeof VerifyStakeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/stakes': typeof StakesRoute
  '/streak': typeof StreakRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/verify/$stakeId': typeof VerifyStakeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/history'
    | '/settings'
    | '/stakes'
    | '/streak'
    | '/match/$matchId'
    | '/verify/$stakeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/history'
    | '/settings'
    | '/stakes'
    | '/streak'
    | '/match/$matchId'
    | '/verify/$stakeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/history'
    | '/settings'
    | '/stakes'
    | '/streak'
    | '/match/$matchId'
    | '/verify/$stakeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  StakesRoute: typeof StakesRoute
  StreakRoute: typeof StreakRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  VerifyStakeIdRoute: typeof VerifyStakeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/streak': {
      id: '/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof StreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakes': {
      id: '/stakes'
      path: '/stakes'
      fullPath: '/stakes'
      preLoaderRoute: typeof StakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$stakeId': {
      id: '/verify/$stakeId'
      path: '/verify/$stakeId'
      fullPath: '/verify/$stakeId'
      preLoaderRoute: typeof VerifyStakeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  StakesRoute: StakesRoute,
  StreakRoute: StreakRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  VerifyStakeIdRoute: VerifyStakeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
